# Generated by Django 3.1.1 on 2020-09-04 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_schooladmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.RegexValidator(code='invalid_number', message='invalid number', regex='\\d{10}')]),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
